TRANSLATIONS = {
    "zh": {
        "site_name": "TruckersMP 视频库", "videos": "我的视频", "upload": "上传", "admin": "管理后台", "users": "用户管理", "login": "登录", "register": "注册", "logout": "退出", "language": "语言", "english": "English", "chinese": "中文", "home": "首页", "save": "保存", "search": "搜索", "status": "状态", "pending": "待审核", "approved": "已通过", "rejected": "已拒绝", "no_videos": "暂无视频", "title": "标题", "description": "描述", "report_id": "举报 ID", "choose_file": "选择视频文件", "no_file": "尚未选择文件", "upload_video": "上传视频", "share": "分享视频", "rejection_reason": "拒绝原因", "resubmit": "重新提交审核", "play_after_approval": "视频审核通过后才能播放或分享。", "original_filename": "原文件名", "none": "无", "moderation_history": "审核历史", "audit_csv": "导出审计 CSV", "all": "全部", "approve": "通过", "reject": "拒绝", "delete": "删除", "reset_share": "重置分享码", "role": "角色", "actions": "操作", "account_status": "账号状态", "quota": "配额", "save_role": "保存角色", "unlock": "解锁", "disable_upload": "禁止上传", "enable_upload": "恢复上传", "system": "系统", "reason": "原因", "ip": "IP", "source": "来源", "time": "时间", "video": "视频", "admin_user": "管理员"},
    "en": {
        "site_name": "TruckersMP Video Library", "videos": "My Videos", "upload": "Upload", "admin": "Admin", "users": "Users", "login": "Log in", "register": "Register", "logout": "Log out", "language": "Language", "english": "English", "chinese": "中文", "home": "Home", "save": "Save", "search": "Search", "status": "Status", "pending": "Pending", "approved": "Approved", "rejected": "Rejected", "no_videos": "No videos", "title": "Title", "description": "Description", "report_id": "Report ID", "choose_file": "Choose video file", "no_file": "No file selected", "upload_video": "Upload video", "share": "Share video", "rejection_reason": "Rejection reason", "resubmit": "Resubmit for review", "play_after_approval": "The video can be played or shared after approval.", "original_filename": "Original filename", "none": "None", "moderation_history": "Moderation history", "audit_csv": "Export audit CSV", "all": "All", "approve": "Approve", "reject": "Reject", "delete": "Delete", "reset_share": "Reset share code", "role": "Role", "actions": "Actions", "account_status": "Account status", "quota": "Quota", "save_role": "Save role", "unlock": "Unlock", "disable_upload": "Disable upload", "enable_upload": "Enable upload", "system": "System", "reason": "Reason", "ip": "IP", "source": "Source", "time": "Time", "video": "Video", "admin_user": "Administrator"}
}

def translate(lang, key):
    return TRANSLATIONS.get(lang, TRANSLATIONS["zh"]).get(key, TRANSLATIONS["zh"].get(key, key))
